# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6898681c3c1983e7274c7cdc41fc96d"
name = "Stock Badge"
application_url = "https://stockbadges.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"

[auth]
redirect_urls = [ "https://stockbadges.vercel.app/api/auth", "https://stockbadges.vercel.app/auth/callback" ]

[app_proxy]
url = "https://stockbadges.vercel.app"
subpath = "stockbadge"
prefix = "apps"

[extensions.theme]
handle = "stockbadge-extension"
