name = "stockbadge"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory"

application_url = "https://stockbadges.vercel.app"

[auth]
redirect_urls = ["https://stockbadges.vercel.app/api/auth", "https://stockbadges.vercel.app/auth/callback"]

[webhooks]
api_version = "2024-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://stockbadges.vercel.app/api/webhooks"
  customer_data_request_url = "https://stockbadges.vercel.app/api/webhooks"
  shop_deletion_url = "https://stockbadges.vercel.app/api/webhooks"
